### ISSUE TITLE
Issues with SES

### ISSUE THREAD

**Issue by apportunities** [neilobremski/gas#1]
For AWS SES, the URI value != the signing value.

Expected URI format is `https://email.{{region}}.amazonaws.com`, but the signed service has to be `ses`. Currently, if you use 'ses' as the service you will get a DNS error. If you use 'email' as the service, AWS returns {"message":"Credential should be scoped to correct service: 'ses'. "}

A fix is modifying a line in your GetHost function:

```
function GetHost(service, region, bucket) {
  // get host name destination of AWS request
  // (S3 includes bucket name in host but no region)
  return [
    (service == "s3" ? bucket : undefined),
    (service == "ses" ? "email" : service), // <----
    (service == "s3" ? undefined : region),
    "amazonaws.com"
  ].filter(Boolean).join(".");
}
```

**Comment by neilobremski** [comment]
@jppty : I've submitted a PR if you'd care to review it
